image:
  repository: davos.fhgr.ch/nlp/orbis2/orbis2-backend
  tag: 1.0.0
  pullPolicy: Always

imagePullSecrets: [ name: regcred ]
nameOverride: ""
fullnameOverride: ""

controller:
  enabled: true
  type: deployment
  replicas: 1

service:
  main:
    type: ClusterIP
    ports:
      http:
        enabled: true
        port: 63012
        protocol: HTTP
        targetPort: 63012

env:
  DB_URL: postgresql.database
  DB_USER:
    valueFrom:
      secretKeyRef:
        name: postgresql-orbis2ng-credentials
        key: postgresql_user
  DB_PASSWORD:
    valueFrom:
      secretKeyRef:
        name: postgresql-orbis2ng-credentials
        key: postgresql_pwd